config/routes.rb
Rails.application.routes.draw do
  root 'cart#index'
  post '/calculate', to: 'cart#calculate'
end

app/models/cart.rb
class Cart
  attr_reader :params

  def initialize(params)
    @params = params
  end

  def products
    @products ||= begin
      return [] unless params
      Product.includes(:offer)
        .where(id: params.map { |item| item['id'] })
    end
  end

  def offers
    @offers ||= products.map(&:offer).compact
  end

  def quantity(product_id)
    quantity = params.select { |item| item['id'].to_i == product_id }
    quantity.first['count'].to_i
  end

  def overall_sum
    @overall_sum ||= begin
      products.to_a.sum { |product| product.price * quantity(product.id) }
    end
  end

  def discount_sum
    @discount_sum ||= begin
      return 0 if offers.blank?

      offers.to_a.sum do |offer|
        offer.get_discount \
          count: quantity(offer.product_id),
          overall_sum: overall_sum
      end
    end
  end

  def total_sum
    overall_sum - discount_sum
  end
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :product
  store_accessor :properties, :product_count, :discount, :type

  def get_discount(count:, overall_sum:)
    return 0 if count < product_count

    case type
    when 'percentage'
      discount * overall_sum / 100
    when 'cash'
      discount
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_one :offer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def index
    @products = Product.all
  end

  def calculate
    cart = Cart.new params[:products]
    response = {
      discount_sum: cart.discount_sum,
      total_sum: cart.total_sum
    }
    render json: response
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cart/index.html.slim
h1 Выберите чай!

p Для добавления/удаления товара кликните по названию.

= form_tag calculate_path, id: 'cart-form' do
  table.table
    tr
      th Название
      th Цена
      th Количество

    - @products.each do |product|
      tr
        td.name = product.name
        td = number_to_currency product.price
        td
          = hidden_field_tag 'products[][id]', product.id, disabled: true
          = text_field_tag 'products[][count]', 1, disabled: true, class: 'quantity'

| Скидка:
span#discount
br

| Сумма заказа с учетом скидки:
span#total

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title = content_for?(:title) ? yield(:title) : "ShoppingCart"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"

  body

    .container
      .row
        .col-lg-9
          = yield